### ISSUE TITLE
Issue in /neurocity/data/store.py

### ISSUE THREAD

**Issue by YantianZha** [akosiorek/hart#7]
Hello,

I met an error when running the training script. The error is below. I added the code to print out the value of len(v) and len(self).
/neurocity/data/store.py", line 87, in reset_data
    assert len(v) == len(self), (len(v), len(self))
AssertionError: (1, 0) 

Thanks!

**Comment by akosiorek** [comment]
Hi @YantianZha; I'm afraid I don't know what the issue is. This line checks if all lists in `self.values` are of equal length and serves as a sanity check. It might be related to the data format you're using. Have you followed the instructions for preparing the dataset I outlined in the README?

**Comment by YantianZha** [comment]
Thanks! I misunderstood "path/to/image/folder" in README. I changed my image path according to the example in code (default='../../data/kitti_tracking/small').
